/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blog: Blog;
    caseStudy: CaseStudy;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    caseStudy: CaseStudySelect<false> | CaseStudySelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  /**
   * Blog post title - slug will update automatically
   */
  title: string;
  featuredImage?: (string | null) | Media;
  type: 'article' | 'video';
  /**
   * Brief summary of the blog post
   */
  excerpt: string;
  /**
   * Choose one or more categories for this post
   */
  categories?:
    | (
        | 'AI'
        | 'Ecommerce'
        | 'Human Insights'
        | 'A/B Testing'
        | 'UX'
        | 'Shopify'
        | 'UX Research'
        | 'AOV'
        | 'Conversion'
        | 'Case Study'
        | 'Growth'
        | 'Retention'
        | 'Product Thinking'
      )[]
    | null;
  /**
   * Choose how the video is provided
   */
  videoSource?: ('upload' | 'embed') | null;
  /**
   * Upload a video file. Use a featured image as the poster/thumbnail.
   */
  videoUpload?: (string | null) | Media;
  /**
   * Paste a YouTube/Vimeo/Wistia URL
   */
  embedUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * Title that appears in search results (recommended: 50-60 characters)
     */
    title?: string | null;
    /**
     * Description that appears in search results (recommended: 150-160 characters)
     */
    description?: string | null;
    /**
     * Image for search results and social sharing (recommended: 1200x630px)
     */
    image?: (string | null) | Media;
    /**
     * Relevant keywords for search engines
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Automatically set to the current user
   */
  author: string | User;
  /**
   * When this post should be published
   */
  publishedAt?: string | null;
  /**
   * If enabled, this post can be shown in the Featured section (max 4 posts)
   */
  isFeatured?: boolean | null;
  /**
   * Auto-generated from title field. Click lock/unlock to control updates.
   */
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudy".
 */
export interface CaseStudy {
  id: string;
  /**
   * Case study title - slug will update automatically
   */
  title: string;
  /**
   * Main image for the case study card and detail page
   */
  featuredImage: string | Media;
  /**
   * Brief summary for the case study card
   */
  description: string;
  /**
   * Choose one or more tags for this case study
   */
  tags: (
    | 'AI'
    | 'Ecommerce'
    | 'Human Insights'
    | 'A/B Testing'
    | 'UX'
    | 'Shopify'
    | 'UX Research'
    | 'AOV'
    | 'Conversion'
    | 'Case Study'
    | 'Growth'
    | 'Retention'
    | 'Agency Life'
    | 'Lean UX'
    | 'Minimalism'
    | 'Dev Strategy'
    | 'Founders'
    | 'Product Thinking'
    | 'Checkout'
  )[];
  /**
   * Key performance metrics and results
   */
  metrics: {
    /**
     * Metric value (e.g., "23%", "5x")
     */
    value: string;
    /**
     * Metric label (e.g., "reduction in churn")
     */
    label: string;
    /**
     * Additional context for the metric
     */
    description?: string | null;
    id?: string | null;
  }[];
  /**
   * Add content sections to build the page
   */
  content?:
    | (
        | HeroSection
        | ResultsSection
        | InsightsSection
        | InsightsListSection
        | ProcessSection
        | BeforeAfterSection
        | ProcessDetailsSection
        | OutcomeSection
        | ContentWithMedia
        | TableOfContents
        | DotSeparator
      )[]
    | null;
  meta?: {
    /**
     * Title that appears in search results (recommended: 50-60 characters)
     */
    title?: string | null;
    /**
     * Description that appears in search results (recommended: 150-160 characters)
     */
    description?: string | null;
    /**
     * Image for search results and social sharing (recommended: 1200x630px)
     */
    image?: (string | null) | Media;
    /**
     * Relevant keywords for search engines
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * When this case study should be published
   */
  publishedAt?: string | null;
  /**
   * Auto-generated from title field. Click lock/unlock to control updates.
   */
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection".
 */
export interface HeroSection {
  /**
   * Main title for the case study
   */
  title: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Client company name
   */
  client: string;
  /**
   * Industry or business category
   */
  industry: string;
  /**
   * Services provided and scope of work
   */
  scope: string;
  /**
   * Project duration (e.g., "8 weeks")
   */
  timeframe: string;
  /**
   * The main challenge the client faced
   */
  challenge: string;
  /**
   * What we did to solve the challenge
   */
  solution: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsSection".
 */
export interface ResultsSection {
  /**
   * Overall results summary description
   */
  summary: string;
  /**
   * Detailed breakdown of results with metrics
   */
  detailedResults: {
    /**
     * Metric value (e.g., "23%", "5x")
     */
    percentage: string;
    /**
     * Metric label (e.g., "reduction in churn")
     */
    metric: string;
    /**
     * Additional context for the metric
     */
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'resultsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsSection".
 */
export interface InsightsSection {
  /**
   * Main heading for the insights section
   */
  title: string;
  /**
   * Main description explaining the analysis approach
   */
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image showing the starting point
   */
  mainImage?: (string | null) | Media;
  /**
   * Caption for the main image
   */
  mainImageCaption?: string | null;
  /**
   * Points about what was already known
   */
  whatWeKnew: {
    point: string;
    id?: string | null;
  }[];
  /**
   * Points about what needed to be learned
   */
  whatWeNeededToLearn: {
    point: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'insightsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsListSection".
 */
export interface InsightsListSection {
  /**
   * Background color for the first item
   */
  startBackground: 'muted' | 'white';
  /**
   * Key insights discovered during analysis
   */
  items: {
    /**
     * Optional small heading above the title
     */
    heading?: string | null;
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'insightsListSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessSection".
 */
export interface ProcessSection {
  /**
   * Summary of the process and changes made
   */
  summary: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterSection".
 */
export interface BeforeAfterSection {
  /**
   * Section title
   */
  title: string;
  /**
   * Main image showing the improvement
   */
  mainImage?: (string | null) | Media;
  /**
   * Caption for the main image
   */
  mainImageCaption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Points about the before state
   */
  before: {
    point: string;
    id?: string | null;
  }[];
  /**
   * Points about the after state
   */
  after: {
    point: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'beforeAfterSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessDetailsSection".
 */
export interface ProcessDetailsSection {
  /**
   * Description of the process improvements
   */
  description: string;
  /**
   * Detailed process steps with images
   */
  details?:
    | {
        /**
         * Step title
         */
        title: string;
        /**
         * Step description
         */
        description: string;
        /**
         * Image showing the process step
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processDetailsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OutcomeSection".
 */
export interface OutcomeSection {
  /**
   * Summary of the overall outcome
   */
  summary: string;
  /**
   * Key results and metrics
   */
  keyResults: {
    /**
     * Result value (e.g., "23%", "5x")
     */
    percentage: string;
    /**
     * Result label (e.g., "reduction in churn")
     */
    metric: string;
    /**
     * Detailed description of the result
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Key takeaways and lessons learned
   */
  takeaways: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'outcomeSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentWithMedia".
 */
export interface ContentWithMedia {
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  textPosition?: ('Left' | 'Right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentWithMedia';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableOfContents".
 */
export interface TableOfContents {
  contents?:
    | {
        header?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableOfContents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DotSeparator".
 */
export interface DotSeparator {
  id?: string | null;
  blockName?: string | null;
  blockType: 'dotSeparator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'caseStudy';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  type?: T;
  excerpt?: T;
  categories?: T;
  videoSource?: T;
  videoUpload?: T;
  embedUrl?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  author?: T;
  publishedAt?: T;
  isFeatured?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudy_select".
 */
export interface CaseStudySelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  description?: T;
  tags?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  content?:
    | T
    | {
        heroSection?: T | HeroSectionSelect<T>;
        resultsSection?: T | ResultsSectionSelect<T>;
        insightsSection?: T | InsightsSectionSelect<T>;
        insightsListSection?: T | InsightsListSectionSelect<T>;
        processSection?: T | ProcessSectionSelect<T>;
        beforeAfterSection?: T | BeforeAfterSectionSelect<T>;
        processDetailsSection?: T | ProcessDetailsSectionSelect<T>;
        outcomeSection?: T | OutcomeSectionSelect<T>;
        contentWithMedia?: T | ContentWithMediaSelect<T>;
        tableOfContents?: T | TableOfContentsSelect<T>;
        dotSeparator?: T | DotSeparatorSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  industry?: T;
  scope?: T;
  timeframe?: T;
  challenge?: T;
  solution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsSection_select".
 */
export interface ResultsSectionSelect<T extends boolean = true> {
  summary?: T;
  detailedResults?:
    | T
    | {
        percentage?: T;
        metric?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsSection_select".
 */
export interface InsightsSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mainImage?: T;
  mainImageCaption?: T;
  whatWeKnew?:
    | T
    | {
        point?: T;
        id?: T;
      };
  whatWeNeededToLearn?:
    | T
    | {
        point?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsListSection_select".
 */
export interface InsightsListSectionSelect<T extends boolean = true> {
  startBackground?: T;
  items?:
    | T
    | {
        heading?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessSection_select".
 */
export interface ProcessSectionSelect<T extends boolean = true> {
  summary?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterSection_select".
 */
export interface BeforeAfterSectionSelect<T extends boolean = true> {
  title?: T;
  mainImage?: T;
  mainImageCaption?: T;
  before?:
    | T
    | {
        point?: T;
        id?: T;
      };
  after?:
    | T
    | {
        point?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessDetailsSection_select".
 */
export interface ProcessDetailsSectionSelect<T extends boolean = true> {
  description?: T;
  details?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OutcomeSection_select".
 */
export interface OutcomeSectionSelect<T extends boolean = true> {
  summary?: T;
  keyResults?:
    | T
    | {
        percentage?: T;
        metric?: T;
        description?: T;
        id?: T;
      };
  takeaways?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentWithMedia_select".
 */
export interface ContentWithMediaSelect<T extends boolean = true> {
  content?: T;
  image?: T;
  textPosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableOfContents_select".
 */
export interface TableOfContentsSelect<T extends boolean = true> {
  contents?:
    | T
    | {
        header?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DotSeparator_select".
 */
export interface DotSeparatorSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'blog';
          value: string | Blog;
        } | null)
      | ({
          relationTo: 'caseStudy';
          value: string | CaseStudy;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}